apiVersion: v1
kind: Service
metadata:
    name: fleetman-queue-service
spec:
    selector:
        app: queue
        release: "1"
    ports:
      - name: http
        protocol: TCP
        port: 8161
        targetPort: 8161
        nodePort: 30010
    type: NodePort
        