apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-service
spec:
  # This defined which pods are going to be represented by the service.
  # Service becomes a network endpoint for eithe rother services or 
  # external users to connect to (e.g. browser)
  selector:
    app: webapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
    ## ClusterIP is only accessable from within the K8S Cluster (Private service)
    ## Nodeport is a port exposed through the Node
