apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      name: webapp-pod
      labels:
        app: webapp
    spec:
      containers:
      -  name: webapp
         image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5